/* tslint:disable */
/* eslint-disable */
/**
 * YAPP 21st ALl2 API 명세서
 * YAPP 21st ALl2 API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 작품 목록의 작품 썸네일 정보
 * @export
 * @interface ArtworkThumbnailDto
 */
export interface ArtworkThumbnailDto {
    /**
     * 작품 ID
     * @type {number}
     * @memberof ArtworkThumbnailDto
     */
    'id': number;
    /**
     * 작품 이미지
     * @type {string}
     * @memberof ArtworkThumbnailDto
     */
    'imageURL': string;
    /**
     * 작품명
     * @type {string}
     * @memberof ArtworkThumbnailDto
     */
    'name': string;
    /**
     * 관람 날짜
     * @type {string}
     * @memberof ArtworkThumbnailDto
     */
    'artist': string;
}
/**
 * 
 * @export
 * @interface ArtworkThumbnailDtoPage
 */
export interface ArtworkThumbnailDtoPage {
    /**
     * 
     * @type {Array<ArtworkThumbnailDto>}
     * @memberof ArtworkThumbnailDtoPage
     */
    'content'?: Array<ArtworkThumbnailDto>;
    /**
     * 
     * @type {PageableObject}
     * @memberof ArtworkThumbnailDtoPage
     */
    'pageable'?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof ArtworkThumbnailDtoPage
     */
    'totalElements'?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkThumbnailDtoPage
     */
    'totalPages'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ArtworkThumbnailDtoPage
     */
    'last'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ArtworkThumbnailDtoPage
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkThumbnailDtoPage
     */
    'number'?: number;
    /**
     * 
     * @type {Sort}
     * @memberof ArtworkThumbnailDtoPage
     */
    'sort'?: Sort;
    /**
     * 
     * @type {number}
     * @memberof ArtworkThumbnailDtoPage
     */
    'numberOfElements'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ArtworkThumbnailDtoPage
     */
    'first'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ArtworkThumbnailDtoPage
     */
    'empty'?: boolean;
}
/**
 * 전시 생성 Request
 * @export
 * @interface CreateArtworkRequestDto
 */
export interface CreateArtworkRequestDto {
    /**
     * 전시 ID
     * @type {number}
     * @memberof CreateArtworkRequestDto
     */
    'postId': number;
    /**
     * s3 이미지 URI. S3 Presigned URL 발급 후 반환한 imageKey 값
     * @type {string}
     * @memberof CreateArtworkRequestDto
     */
    'imageUri': string;
    /**
     * 작가 이름
     * @type {string}
     * @memberof CreateArtworkRequestDto
     */
    'artist'?: string;
    /**
     * 작품명
     * @type {string}
     * @memberof CreateArtworkRequestDto
     */
    'name'?: string;
    /**
     * 작품 할당 태그
     * @type {Array<CreateArtworkTagDto>}
     * @memberof CreateArtworkRequestDto
     */
    'tags'?: Array<CreateArtworkTagDto>;
}
/**
 * 전시 작품 생성 Response
 * @export
 * @interface CreateArtworkResponseDto
 */
export interface CreateArtworkResponseDto {
    /**
     * 전시 작품 아이디
     * @type {number}
     * @memberof CreateArtworkResponseDto
     */
    'id'?: number;
}
/**
 * 전시 작품 추가시 할당될 태그 정보
 * @export
 * @interface CreateArtworkTagDto
 */
export interface CreateArtworkTagDto {
    /**
     * 태그 ID. 기존에 존재한 태그를 작품에 추가할 경우 제공되어야함.
     * @type {number}
     * @memberof CreateArtworkTagDto
     */
    'tagId'?: number;
    /**
     * 태그 이름. 새롭게 태그를 생성하여 작품에 추가할 경우 태그 이름만 제공되어야함.
     * @type {string}
     * @memberof CreateArtworkTagDto
     */
    'tagName': string;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponse
     */
    'status'?: number;
    /**
     * 
     * @type {Array<FieldError>}
     * @memberof ErrorResponse
     */
    'errors'?: Array<FieldError>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'code'?: string;
}
/**
 * 
 * @export
 * @interface FieldError
 */
export interface FieldError {
    /**
     * 
     * @type {string}
     * @memberof FieldError
     */
    'field'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldError
     */
    'value'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldError
     */
    'reason'?: string;
}
/**
 * 
 * @export
 * @interface Pageable
 */
export interface Pageable {
    /**
     * 
     * @type {number}
     * @memberof Pageable
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pageable
     */
    'size'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Pageable
     */
    'sort'?: Array<string>;
}
/**
 * 
 * @export
 * @interface PageableObject
 */
export interface PageableObject {
    /**
     * 
     * @type {number}
     * @memberof PageableObject
     */
    'offset'?: number;
    /**
     * 
     * @type {Sort}
     * @memberof PageableObject
     */
    'sort'?: Sort;
    /**
     * 
     * @type {number}
     * @memberof PageableObject
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageableObject
     */
    'pageSize'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageableObject
     */
    'paged'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageableObject
     */
    'unpaged'?: boolean;
}
/**
 * 
 * @export
 * @interface Sort
 */
export interface Sort {
    /**
     * 
     * @type {boolean}
     * @memberof Sort
     */
    'empty'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Sort
     */
    'sorted'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Sort
     */
    'unsorted'?: boolean;
}

/**
 * ArtworkControllerApi - axios parameter creator
 * @export
 */
export const ArtworkControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 작품(이미지)를 전시에 추가
         * @summary 전시 작품 추가
         * @param {CreateArtworkRequestDto} createArtworkRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createArtwork: async (createArtworkRequestDto: CreateArtworkRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createArtworkRequestDto' is not null or undefined
            assertParamExists('createArtwork', 'createArtworkRequestDto', createArtworkRequestDto)
            const localVarPath = `/artwork`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createArtworkRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 전시 상세 페이지의 작품 목록 조회
         * @summary 전시의 작품 목록 조회
         * @param {number} id 전시 ID
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArtworkPageFromPost: async (id: number, pageable: Pageable, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getArtworkPageFromPost', 'id', id)
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getArtworkPageFromPost', 'pageable', pageable)
            const localVarPath = `/artwork/post/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                localVarQueryParameter['pageable'] = pageable;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ArtworkControllerApi - functional programming interface
 * @export
 */
export const ArtworkControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ArtworkControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 작품(이미지)를 전시에 추가
         * @summary 전시 작품 추가
         * @param {CreateArtworkRequestDto} createArtworkRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createArtwork(createArtworkRequestDto: CreateArtworkRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateArtworkResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createArtwork(createArtworkRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 전시 상세 페이지의 작품 목록 조회
         * @summary 전시의 작품 목록 조회
         * @param {number} id 전시 ID
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArtworkPageFromPost(id: number, pageable: Pageable, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ArtworkThumbnailDtoPage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getArtworkPageFromPost(id, pageable, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ArtworkControllerApi - factory interface
 * @export
 */
export const ArtworkControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ArtworkControllerApiFp(configuration)
    return {
        /**
         * 작품(이미지)를 전시에 추가
         * @summary 전시 작품 추가
         * @param {CreateArtworkRequestDto} createArtworkRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createArtwork(createArtworkRequestDto: CreateArtworkRequestDto, options?: any): AxiosPromise<CreateArtworkResponseDto> {
            return localVarFp.createArtwork(createArtworkRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 전시 상세 페이지의 작품 목록 조회
         * @summary 전시의 작품 목록 조회
         * @param {number} id 전시 ID
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArtworkPageFromPost(id: number, pageable: Pageable, options?: any): AxiosPromise<ArtworkThumbnailDtoPage> {
            return localVarFp.getArtworkPageFromPost(id, pageable, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ArtworkControllerApi - object-oriented interface
 * @export
 * @class ArtworkControllerApi
 * @extends {BaseAPI}
 */
export class ArtworkControllerApi extends BaseAPI {
    /**
     * 작품(이미지)를 전시에 추가
     * @summary 전시 작품 추가
     * @param {CreateArtworkRequestDto} createArtworkRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArtworkControllerApi
     */
    public createArtwork(createArtworkRequestDto: CreateArtworkRequestDto, options?: AxiosRequestConfig) {
        return ArtworkControllerApiFp(this.configuration).createArtwork(createArtworkRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 전시 상세 페이지의 작품 목록 조회
     * @summary 전시의 작품 목록 조회
     * @param {number} id 전시 ID
     * @param {Pageable} pageable 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArtworkControllerApi
     */
    public getArtworkPageFromPost(id: number, pageable: Pageable, options?: AxiosRequestConfig) {
        return ArtworkControllerApiFp(this.configuration).getArtworkPageFromPost(id, pageable, options).then((request) => request(this.axios, this.basePath));
    }
}


